package com.arnold.rbac.dao;

import com.arnold.rbac.model.SysElement;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SysElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    int insert(SysElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    int insertSelective(SysElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    SysElement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_element
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysElement record);

    List<SysElement> getElementList();

	Integer deleteBatch(List<Integer> elementIds);

	List<SysElement> getElementsByMenuIds(List<Integer> menuIds);


}