package com.arnold.rbac.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_element
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysElement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属菜单页面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.menu_id
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.permission_id
     *
     * @mbg.generated
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.is_usable
     *
     * @mbg.generated
     */
    private Boolean isUsable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.editor
     *
     * @mbg.generated
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.edit_date
     *
     * @mbg.generated
     */
    private Date editDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_element.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.id
     *
     * @return the value of sys_element.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.id
     *
     * @param id the value for sys_element.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.name
     *
     * @return the value of sys_element.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.name
     *
     * @param name the value for sys_element.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.menu_id
     *
     * @return the value of sys_element.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.menu_id
     *
     * @param menuId the value for sys_element.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.permission_id
     *
     * @return the value of sys_element.permission_id
     *
     * @mbg.generated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.permission_id
     *
     * @param permissionId the value for sys_element.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.is_usable
     *
     * @return the value of sys_element.is_usable
     *
     * @mbg.generated
     */
    public Boolean getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.is_usable
     *
     * @param isUsable the value for sys_element.is_usable
     *
     * @mbg.generated
     */
    public void setIsUsable(Boolean isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.creater
     *
     * @return the value of sys_element.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.creater
     *
     * @param creater the value for sys_element.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.create_date
     *
     * @return the value of sys_element.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.create_date
     *
     * @param createDate the value for sys_element.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.editor
     *
     * @return the value of sys_element.editor
     *
     * @mbg.generated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.editor
     *
     * @param editor the value for sys_element.editor
     *
     * @mbg.generated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.edit_date
     *
     * @return the value of sys_element.edit_date
     *
     * @mbg.generated
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.edit_date
     *
     * @param editDate the value for sys_element.edit_date
     *
     * @mbg.generated
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_element.is_del
     *
     * @return the value of sys_element.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_element.is_del
     *
     * @param isDel the value for sys_element.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

	/**
	 * 菜单的permission主要就是显示作用。
	 */
	SysPermission permission;

	public SysPermission getPermission() {
		return permission;
	}

	public void setPermission(SysPermission permission) {
		this.permission = permission;
	}
}